# Generated by Django 5.1.4 on 2025-04-08 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_card_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='going_alone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='trump_caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_trumps', to='homepage.player'),
        ),
    ]
