# Generated by Django 5.1.4 on 2025-01-09 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_game_trump_suit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='trump_suit',
        ),
        migrations.AddField(
            model_name='game',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_dealer', to='homepage.player'),
        ),
    ]
