# Generated by Django 5.1.4 on 2025-01-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_game_trump_suit_game_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trump_suit',
            field=models.CharField(choices=[('hearts', 'Hearts'), ('diamonds', 'Diamonds'), ('clubs', 'Clubs'), ('spades', 'Spades')], default='hearts', max_length=10),
            preserve_default=False,
        ),
    ]
