# Generated by Django 5.1.4 on 2025-01-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_game_trump_suit'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team1_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_points',
            field=models.IntegerField(default=0),
        ),
    ]
