# Generated by Django 5.1.4 on 2025-01-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_game_team1_points_game_team2_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playedcard',
            unique_together={('player', 'card')},
        ),
    ]
