# Generated by Django 5.1.4 on 2025-01-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_playedcard_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedcard',
            name='hand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='played_cards', to='homepage.hand'),
        ),
    ]
