# Generated by Django 5.1.4 on 2025-02-17 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_gameresult_winner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playedcard',
            unique_together=set(),
        ),
    ]
