# Generated by Django 5.1.4 on 2025-02-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_game_trump_suit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='trump_suit',
            field=models.CharField(blank=True, choices=[('hearts', 'Hearts'), ('diamonds', 'Diamonds'), ('clubs', 'Clubs'), ('spades', 'Spades')], max_length=10, null=True),
        ),
    ]
